sonar.projectKey=simple-cloud-lifecycle
sonar.projectName=Simple Cloud Lifecycle
sonar.projectVersion=1.0

sonar.sources=app,components
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,tailwind.config.ts,next.config.mjs