# SonarQube Project Identification
sonar.projectKey=optravc_Simple-cloud-lifecylce
sonar.organization=optravc-dev

# Exclude generated report artifacts and HTML files from SonarQube scan
sonar.exclusions=AWS/infracost-report.html,AWS/*.html,**/*.html,**/docs/**