# dockerfile 

FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY  go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app-api ./cmd/api/main.go


FROM alpine:latest

WORKDIR /root
COPY --from=builder /app-api ./

CMD ["./app-api"]